"""
seed_mock_data.py — Populate MongoDB with development/demo data.

Run from the backend directory:
    python scripts/seed_mock_data.py

Reads all 235 Suffolk County census tracts from:
    backend/data/boston_tracts.geojson   (generated by convert_shapefile.py)

Risk scores for 10 featured neighbourhoods come from TRACT_RISK_SCORES.
All other tracts get deterministic varied scores (same algorithm as
src/data/censusTracts.ts) so the choropleth looks realistic.

Collections written:
  - census_tracts  (235 tracts — real Suffolk County geometry + risk scores)
  - food_resources (15 resources spread across high-risk tracts)
  - city_stats     (1 singleton document)
"""
import json
import math
import os
import sys
from pathlib import Path

# ── Bootstrap Django settings ─────────────────────────────────────────────────
if "django" not in sys.modules or not os.environ.get("DJANGO_SETTINGS_MODULE"):
    sys.path.insert(0, str(Path(__file__).resolve().parents[1]))
    os.environ.setdefault("DJANGO_SETTINGS_MODULE", "config.settings")

    from dotenv import load_dotenv
    load_dotenv(Path(__file__).resolve().parents[1] / ".env")

    import django
    django.setup()

from core.db import city_stats_col, resources_col, tracts_col  # noqa: E402

# ── Paths ─────────────────────────────────────────────────────────────────────
BACKEND_DIR  = Path(__file__).resolve().parents[1]
GEOJSON_PATH = BACKEND_DIR / "data" / "boston_tracts.geojson"

# ─────────────────────────────────────────────────────────────────────────────
# Risk score lookup — mirrors src/data/tractRiskScores.ts exactly.
# Keys are 11-digit GEOIDs.
# ─────────────────────────────────────────────────────────────────────────────

TRACT_RISK_SCORES = {
    "25025081600": dict(
        tract_name="Roxbury", food_risk_score=0.88, equity_score=0.41,
        transit_coverage=0.62, food_insecurity_rate=0.34, poverty_rate=0.41,
        snap_rate=0.38, population=8200, vulnerability_index=0.79,
        need_score=0.85, supply_score=0.22,
    ),
    "25025092101": dict(
        tract_name="Dorchester North", food_risk_score=0.82, equity_score=0.48,
        transit_coverage=0.67, food_insecurity_rate=0.29, poverty_rate=0.36,
        snap_rate=0.33, population=6800, vulnerability_index=0.71,
        need_score=0.78, supply_score=0.28,
    ),
    "25025092301": dict(
        tract_name="Dorchester South", food_risk_score=0.79, equity_score=0.50,
        transit_coverage=0.65, food_insecurity_rate=0.27, poverty_rate=0.33,
        snap_rate=0.30, population=7100, vulnerability_index=0.68,
        need_score=0.75, supply_score=0.31,
    ),
    "25025120400": dict(
        tract_name="Mattapan", food_risk_score=0.76, equity_score=0.52,
        transit_coverage=0.58, food_insecurity_rate=0.26, poverty_rate=0.31,
        snap_rate=0.28, population=5900, vulnerability_index=0.70,
        need_score=0.72, supply_score=0.29,
    ),
    "25025000202": dict(
        tract_name="East Boston", food_risk_score=0.68, equity_score=0.55,
        transit_coverage=0.60, food_insecurity_rate=0.22, poverty_rate=0.28,
        snap_rate=0.24, population=9200, vulnerability_index=0.61,
        need_score=0.65, supply_score=0.38,
    ),
    "25025130400": dict(
        tract_name="Hyde Park", food_risk_score=0.63, equity_score=0.58,
        transit_coverage=0.55, food_insecurity_rate=0.20, poverty_rate=0.25,
        snap_rate=0.21, population=5200, vulnerability_index=0.55,
        need_score=0.60, supply_score=0.42,
    ),
    "25025080900": dict(
        tract_name="South End", food_risk_score=0.48, equity_score=0.66,
        transit_coverage=0.82, food_insecurity_rate=0.14, poverty_rate=0.18,
        snap_rate=0.15, population=7800, vulnerability_index=0.38,
        need_score=0.42, supply_score=0.60,
    ),
    "25025100800": dict(
        tract_name="Jamaica Plain", food_risk_score=0.42, equity_score=0.70,
        transit_coverage=0.78, food_insecurity_rate=0.12, poverty_rate=0.16,
        snap_rate=0.13, population=6400, vulnerability_index=0.33,
        need_score=0.38, supply_score=0.65,
    ),
    "25025000301": dict(
        tract_name="Charlestown", food_risk_score=0.28, equity_score=0.80,
        transit_coverage=0.88, food_insecurity_rate=0.08, poverty_rate=0.10,
        snap_rate=0.08, population=4100, vulnerability_index=0.20,
        need_score=0.22, supply_score=0.75,
    ),
    "25025030100": dict(
        tract_name="Downtown", food_risk_score=0.18, equity_score=0.88,
        transit_coverage=0.96, food_insecurity_rate=0.06, poverty_rate=0.08,
        snap_rate=0.05, population=3200, vulnerability_index=0.12,
        need_score=0.15, supply_score=0.88,
    ),
}

DEFAULT_POPULATION = 3500


def _deterministic_risk(geoid: str) -> float:
    """Mirror of deterministicRisk() in censusTracts.ts."""
    n   = int(geoid[-5:]) if geoid[-5:].isdigit() else 0
    mix = (n * 1619 + 37 * (n % 97) + 11) % 100
    if mix < 20:  return round(0.15 + (mix / 20) * 0.15, 4)
    if mix < 55:  return round(0.30 + ((mix - 20) / 35) * 0.20, 4)
    if mix < 85:  return round(0.50 + ((mix - 55) / 30) * 0.20, 4)
    return              round(0.70 + ((mix - 85) / 15) * 0.18, 4)


def _default_scores(geoid: str, namelsad: str) -> dict:
    risk = _deterministic_risk(geoid)
    return dict(
        tract_name=namelsad,
        food_risk_score=risk,
        equity_score=round(0.95 - risk, 2),
        transit_coverage=round(0.55 + (1 - risk) * 0.4, 2),
        food_insecurity_rate=round(risk * 0.38, 2),
        poverty_rate=round(risk * 0.44, 2),
        snap_rate=round(risk * 0.50, 2),
        population=DEFAULT_POPULATION,
        vulnerability_index=round(risk * 0.92, 2),
        need_score=round(risk * 0.95, 2),
        supply_score=round(0.90 - risk * 0.75, 2),
    )


def build_tracts_from_geojson() -> list:
    """Read boston_tracts.geojson and return a list of tract dicts for MongoDB."""
    if not GEOJSON_PATH.exists():
        print(f"ERROR: {GEOJSON_PATH} not found.")
        print("  Run: python scripts/convert_shapefile.py")
        sys.exit(1)

    with GEOJSON_PATH.open(encoding="utf-8") as f:
        geojson = json.load(f)

    tracts = []
    for feature in geojson["features"]:
        props   = feature.get("properties", {})
        geoid   = props.get("GEOID", "")
        namelsad = props.get("NAMELSAD", f"Tract {props.get('TRACTCE','')}")

        if geoid in TRACT_RISK_SCORES:
            scores = TRACT_RISK_SCORES[geoid]
        else:
            scores = _default_scores(geoid, namelsad)

        tractce = props.get("TRACTCE", "000000")
        numeric_id = int(tractce) if tractce.isdigit() else 0

        tracts.append({
            "tract_id":   geoid,
            "numeric_id": numeric_id,
            "geometry":   feature["geometry"],
            **scores,
        })

    return tracts


# ─────────────────────────────────────────────────────────────────────────────
# Food Resources (unchanged — 15 resources spread across high-risk tracts)
# ─────────────────────────────────────────────────────────────────────────────

RESOURCES = [
    # ── Roxbury ───────────────────────────────────────────────────────────────
    {
        "resource_id":  "dudley-farmers-market-310624",
        "name":         "Dudley Farmers Market",
        "type":         "market",
        "address":      "427 Dudley St, Boston, MA 02119",
        "coordinates":  [-71.0832, 42.3277],
        "snap":         True,
        "free":         False,
        "tract_id":     "25025081600",
        "source":       "USDA",
    },
    {
        "resource_id":  "tropical-foods-international-abc123",
        "name":         "Tropical Foods International",
        "type":         "grocery",
        "address":      "450 Melnea Cass Blvd, Roxbury, MA 02119",
        "coordinates":  [-71.0823, 42.3311],
        "snap":         True,
        "free":         False,
        "tract_id":     "25025081600",
        "source":       "USDA",
    },
    # ── Dorchester North ──────────────────────────────────────────────────────
    {
        "resource_id":  "dorchester-winter-farmers-market-310622",
        "name":         "Dorchester Winter Farmers' Market",
        "type":         "market",
        "address":      "6 Norfolk St, Boston, MA 02124",
        "coordinates":  [-71.0671, 42.3049],
        "snap":         True,
        "free":         False,
        "tract_id":     "25025092101",
        "source":       "USDA",
    },
    {
        "resource_id":  "truong-thinh-ii-market-def456",
        "name":         "Truong Thinh II Market",
        "type":         "grocery",
        "address":      "1305 Dorchester Ave, Dorchester, MA 02122",
        "coordinates":  [-71.0682, 42.3022],
        "snap":         True,
        "free":         False,
        "tract_id":     "25025092101",
        "source":       "USDA",
    },
    # ── Mattapan ──────────────────────────────────────────────────────────────
    {
        "resource_id":  "mattapan-farmers-market-310663",
        "name":         "Mattapan Farmers' Market",
        "type":         "market",
        "address":      "525 River St, Mattapan, MA 02126",
        "coordinates":  [-71.0928, 42.2730],
        "snap":         True,
        "free":         False,
        "tract_id":     "25025120400",
        "source":       "USDA",
    },
    {
        "resource_id":  "community-servings-food-pantry-ghi789",
        "name":         "Community Servings Food Pantry",
        "type":         "pantry",
        "address":      "18 Marbury Terrace, Jamaica Plain, MA 02130",
        "coordinates":  [-71.1115, 42.3123],
        "snap":         False,
        "free":         True,
        "tract_id":     "25025120400",
        "source":       "USDA",
    },
    # ── East Boston ───────────────────────────────────────────────────────────
    {
        "resource_id":  "east-boston-grocery-jkl012",
        "name":         "Eagle Market (East Boston)",
        "type":         "grocery",
        "address":      "198 Maverick St, East Boston, MA 02128",
        "coordinates":  [-71.0378, 42.3710],
        "snap":         True,
        "free":         False,
        "tract_id":     "25025000202",
        "source":       "USDA",
    },
    {
        "resource_id":  "east-boston-pantry-mno345",
        "name":         "East Boston Neighborhood Health Center Food Pantry",
        "type":         "pantry",
        "address":      "10 Gove St, East Boston, MA 02128",
        "coordinates":  [-71.0388, 42.3678],
        "snap":         False,
        "free":         True,
        "tract_id":     "25025000202",
        "source":       "seed",
    },
    # ── Hyde Park ─────────────────────────────────────────────────────────────
    {
        "resource_id":  "hyde-park-star-market-pqr678",
        "name":         "Star Market Hyde Park",
        "type":         "grocery",
        "address":      "1377 Hyde Park Ave, Hyde Park, MA 02136",
        "coordinates":  [-71.1264, 42.2558],
        "snap":         True,
        "free":         False,
        "tract_id":     "25025130400",
        "source":       "USDA",
    },
    # ── Jamaica Plain ─────────────────────────────────────────────────────────
    {
        "resource_id":  "community-servings-farmers-market-310614",
        "name":         "Community Servings' Farmers' Market",
        "type":         "market",
        "address":      "18 Marbury Terrace, Jamaica Plain, MA 02130",
        "coordinates":  [-71.1115, 42.3123],
        "snap":         False,
        "free":         False,
        "tract_id":     "25025100800",
        "source":       "USDA",
    },
    {
        "resource_id":  "whole-foods-jp-stu901",
        "name":         "Whole Foods Market (Jamaica Plain)",
        "type":         "grocery",
        "address":      "415 Centre St, Jamaica Plain, MA 02130",
        "coordinates":  [-71.1131, 42.3172],
        "snap":         True,
        "free":         False,
        "tract_id":     "25025100800",
        "source":       "seed",
    },
    # ── South End ─────────────────────────────────────────────────────────────
    {
        "resource_id":  "south-end-food-pantry-vwx234",
        "name":         "South End Food Pantry",
        "type":         "pantry",
        "address":      "95 Berkeley St, Boston, MA 02116",
        "coordinates":  [-71.0694, 42.3467],
        "snap":         False,
        "free":         True,
        "tract_id":     "25025080900",
        "source":       "seed",
    },
    # ── Charlestown ───────────────────────────────────────────────────────────
    {
        "resource_id":  "charlestown-market-basket-yza567",
        "name":         "Market Basket (Charlestown)",
        "type":         "grocery",
        "address":      "3 Rutherford Ave, Charlestown, MA 02129",
        "coordinates":  [-71.0679, 42.3785],
        "snap":         True,
        "free":         False,
        "tract_id":     "25025000301",
        "source":       "seed",
    },
    # ── Downtown ──────────────────────────────────────────────────────────────
    {
        "resource_id":  "boston-public-market-310596",
        "name":         "Boston Public Market on the Greenway",
        "type":         "market",
        "address":      "136 Blackstone St, Boston, MA 02202",
        "coordinates":  [-71.0545, 42.3605],
        "snap":         True,
        "free":         False,
        "tract_id":     "25025030100",
        "source":       "USDA",
    },
    # ── Allston-Brighton (mobile unit) ────────────────────────────────────────
    {
        "resource_id":  "gb-mobile-food-truck-bcd890",
        "name":         "Greater Boston Food Bank Mobile Market",
        "type":         "mobile",
        "address":      "20 Fordham Rd, Brighton, MA 02135",
        "coordinates":  [-71.1512, 42.3502],
        "snap":         True,
        "free":         True,
        "tract_id":     None,
        "source":       "seed",
    },
]


# ─────────────────────────────────────────────────────────────────────────────
# Seed runner
# ─────────────────────────────────────────────────────────────────────────────

def seed():
    print("=== FoodGrid Boston — seed_mock_data ===\n")

    # ── Tracts ────────────────────────────────────────────────────────────────
    tracts = build_tracts_from_geojson()
    print(f"Loaded {len(tracts)} tracts from {GEOJSON_PATH.name}.")

    col_t = tracts_col()
    # Clear stale tracts so old FIPS codes from previous seeds don't accumulate
    deleted = col_t.delete_many({}).deleted_count
    if deleted:
        print(f"  Cleared {deleted} stale tracts.")
    t_upserted = 0
    for tract in tracts:
        r = col_t.update_one(
            {"tract_id": tract["tract_id"]},
            {"$set": tract},
            upsert=True,
        )
        if r.upserted_id or r.modified_count:
            t_upserted += 1
    print(f"Tracts   : {t_upserted}/{len(tracts)} upserted.")

    # ── Resources ─────────────────────────────────────────────────────────────
    col_r = resources_col()
    r_upserted = 0
    for resource in RESOURCES:
        r = col_r.update_one(
            {"resource_id": resource["resource_id"]},
            {"$set": resource},
            upsert=True,
        )
        if r.upserted_id or r.modified_count:
            r_upserted += 1
    print(f"Resources: {r_upserted}/{len(RESOURCES)} upserted.")

    # ── City stats ────────────────────────────────────────────────────────────
    # Compute from the loaded tract data for accuracy
    scores = [t["food_risk_score"] for t in tracts]
    avg_equity = round(sum(1 - s for s in scores) / len(scores), 3)
    avg_transit = round(sum(t["transit_coverage"] for t in tracts) / len(tracts), 3)
    high_risk   = sum(1 for s in scores if s >= 0.65)

    city_stats = {
        "_id":             "singleton",
        "_type":           "city_stats",
        "equity_score":    avg_equity,
        "transit_coverage": avg_transit,
        "high_risk_tracts": high_risk,
        "total_tracts":    len(tracts),
    }
    city_stats_col().update_one(
        {"_id": "singleton"},
        {"$set": city_stats},
        upsert=True,
    )
    print(f"City stats: updated (total_tracts={len(tracts)}, high_risk={high_risk}).")

    print("\nDone. MongoDB collections are ready for development.")


if __name__ == "__main__":
    seed()
