"""
seed_mock_data.py — Populate MongoDB with development/demo data.

Run from the backend directory:
    python scripts/seed_mock_data.py

Reads all 235 Suffolk County census tracts from:
    backend/data/boston_tracts.geojson   (generated by convert_shapefile.py)

Risk scores for 10 featured neighbourhoods come from TRACT_RISK_SCORES.
All other tracts get deterministic varied scores (same algorithm as
src/data/censusTracts.ts) so the choropleth looks realistic.

Collections written:
  - census_tracts  (235 tracts — real Suffolk County geometry + risk scores)
  - food_resources (15 resources spread across high-risk tracts)
  - city_stats     (1 singleton document)
"""
import json
import math
import os
import sys
from pathlib import Path

# ── Bootstrap Django settings ─────────────────────────────────────────────────
if "django" not in sys.modules or not os.environ.get("DJANGO_SETTINGS_MODULE"):
    sys.path.insert(0, str(Path(__file__).resolve().parents[1]))
    os.environ.setdefault("DJANGO_SETTINGS_MODULE", "config.settings")

    from dotenv import load_dotenv
    load_dotenv(Path(__file__).resolve().parents[1] / ".env")

    import django
    django.setup()

from core.db import city_stats_col, resources_col, tracts_col  # noqa: E402

# ── Paths ─────────────────────────────────────────────────────────────────────
BACKEND_DIR  = Path(__file__).resolve().parents[1]
GEOJSON_PATH = BACKEND_DIR / "data" / "boston_tracts.geojson"

# ─────────────────────────────────────────────────────────────────────────────
# Risk score lookup — mirrors src/data/tractRiskScores.ts exactly.
# Keys are 11-digit GEOIDs.
# ─────────────────────────────────────────────────────────────────────────────

TRACT_RISK_SCORES = {
    "25025081600": dict(
        tract_name="Roxbury", food_risk_score=0.88, equity_score=0.41,
        transit_coverage=0.62, food_insecurity_rate=0.34, poverty_rate=0.41,
        snap_rate=0.38, population=8200, vulnerability_index=0.79,
        need_score=0.85, supply_score=0.22,
    ),
    "25025092101": dict(
        tract_name="Dorchester North", food_risk_score=0.82, equity_score=0.48,
        transit_coverage=0.67, food_insecurity_rate=0.29, poverty_rate=0.36,
        snap_rate=0.33, population=6800, vulnerability_index=0.71,
        need_score=0.78, supply_score=0.28,
    ),
    "25025092301": dict(
        tract_name="Dorchester South", food_risk_score=0.79, equity_score=0.50,
        transit_coverage=0.65, food_insecurity_rate=0.27, poverty_rate=0.33,
        snap_rate=0.30, population=7100, vulnerability_index=0.68,
        need_score=0.75, supply_score=0.31,
    ),
    "25025120400": dict(
        tract_name="Mattapan", food_risk_score=0.76, equity_score=0.52,
        transit_coverage=0.58, food_insecurity_rate=0.26, poverty_rate=0.31,
        snap_rate=0.28, population=5900, vulnerability_index=0.70,
        need_score=0.72, supply_score=0.29,
    ),
    "25025000202": dict(
        tract_name="East Boston", food_risk_score=0.68, equity_score=0.55,
        transit_coverage=0.60, food_insecurity_rate=0.22, poverty_rate=0.28,
        snap_rate=0.24, population=9200, vulnerability_index=0.61,
        need_score=0.65, supply_score=0.38,
    ),
    "25025130400": dict(
        tract_name="Hyde Park", food_risk_score=0.63, equity_score=0.58,
        transit_coverage=0.55, food_insecurity_rate=0.20, poverty_rate=0.25,
        snap_rate=0.21, population=5200, vulnerability_index=0.55,
        need_score=0.60, supply_score=0.42,
    ),
    "25025080900": dict(
        tract_name="South End", food_risk_score=0.48, equity_score=0.66,
        transit_coverage=0.82, food_insecurity_rate=0.14, poverty_rate=0.18,
        snap_rate=0.15, population=7800, vulnerability_index=0.38,
        need_score=0.42, supply_score=0.60,
    ),
    "25025100800": dict(
        tract_name="Jamaica Plain", food_risk_score=0.42, equity_score=0.70,
        transit_coverage=0.78, food_insecurity_rate=0.12, poverty_rate=0.16,
        snap_rate=0.13, population=6400, vulnerability_index=0.33,
        need_score=0.38, supply_score=0.65,
    ),
    "25025000301": dict(
        tract_name="Charlestown", food_risk_score=0.28, equity_score=0.80,
        transit_coverage=0.88, food_insecurity_rate=0.08, poverty_rate=0.10,
        snap_rate=0.08, population=4100, vulnerability_index=0.20,
        need_score=0.22, supply_score=0.75,
    ),
    "25025030100": dict(
        tract_name="Downtown", food_risk_score=0.18, equity_score=0.88,
        transit_coverage=0.96, food_insecurity_rate=0.06, poverty_rate=0.08,
        snap_rate=0.05, population=3200, vulnerability_index=0.12,
        need_score=0.15, supply_score=0.88,
    ),
}

DEFAULT_POPULATION = 3500


def _deterministic_risk(geoid: str) -> float:
    """Mirror of deterministicRisk() in censusTracts.ts."""
    n   = int(geoid[-5:]) if geoid[-5:].isdigit() else 0
    mix = (n * 1619 + 37 * (n % 97) + 11) % 100
    if mix < 20:  return round(0.15 + (mix / 20) * 0.15, 4)
    if mix < 55:  return round(0.30 + ((mix - 20) / 35) * 0.20, 4)
    if mix < 85:  return round(0.50 + ((mix - 55) / 30) * 0.20, 4)
    return              round(0.70 + ((mix - 85) / 15) * 0.18, 4)


def _default_scores(geoid: str, namelsad: str) -> dict:
    risk = _deterministic_risk(geoid)
    return dict(
        tract_name=namelsad,
        food_risk_score=risk,
        equity_score=round(0.95 - risk, 2),
        transit_coverage=round(0.55 + (1 - risk) * 0.4, 2),
        food_insecurity_rate=round(risk * 0.38, 2),
        poverty_rate=round(risk * 0.44, 2),
        snap_rate=round(risk * 0.50, 2),
        population=DEFAULT_POPULATION,
        vulnerability_index=round(risk * 0.92, 2),
        need_score=round(risk * 0.95, 2),
        supply_score=round(0.90 - risk * 0.75, 2),
    )


def build_tracts_from_geojson() -> list:
    """Read boston_tracts.geojson and return a list of tract dicts for MongoDB."""
    if not GEOJSON_PATH.exists():
        print(f"ERROR: {GEOJSON_PATH} not found.")
        print("  Run: python scripts/convert_shapefile.py")
        sys.exit(1)

    with GEOJSON_PATH.open(encoding="utf-8") as f:
        geojson = json.load(f)

    tracts = []
    for feature in geojson["features"]:
        props   = feature.get("properties", {})
        geoid   = props.get("GEOID", "")
        namelsad = props.get("NAMELSAD", f"Tract {props.get('TRACTCE','')}")

        if geoid in TRACT_RISK_SCORES:
            scores = TRACT_RISK_SCORES[geoid]
        else:
            scores = _default_scores(geoid, namelsad)

        tractce = props.get("TRACTCE", "000000")
        numeric_id = int(tractce) if tractce.isdigit() else 0

        tracts.append({
            "tract_id":   geoid,
            "numeric_id": numeric_id,
            "geometry":   feature["geometry"],
            **scores,
        })

    return tracts


# ─────────────────────────────────────────────────────────────────────────────
# Food Resources (unchanged — 15 resources spread across high-risk tracts)
# ─────────────────────────────────────────────────────────────────────────────

RESOURCES = [
    # ── Brookline / Fenway (near default user location) ──────────────────────
    {"resource_id":"seed-b01","name":"Trader Joe's Coolidge Corner","type":"grocery",
     "address":"1317 Beacon St, Brookline, MA 02446","coordinates":[-71.1239,42.3413],
     "snap":True,"free":False,"hours":"Daily 8am-9pm","tract_id":"","source":"seed"},
    {"resource_id":"seed-b02","name":"Star Market Fenway","type":"grocery",
     "address":"53 Huntington Ave, Boston, MA 02116","coordinates":[-71.0870,42.3469],
     "snap":True,"free":False,"tract_id":"","source":"seed"},
    {"resource_id":"seed-b03","name":"Whole Foods Fenway","type":"grocery",
     "address":"15 Westland Ave, Boston, MA 02115","coordinates":[-71.0998,42.3449],
     "snap":True,"free":False,"hours":"Daily 7am-10pm","tract_id":"","source":"seed"},
    {"resource_id":"seed-b04","name":"CVS Brookline Village","type":"grocery",
     "address":"1199 Boylston St, Brookline, MA 02467","coordinates":[-71.1199,42.3518],
     "snap":False,"free":False,"tract_id":"","source":"seed"},
    {"resource_id":"seed-b05","name":"Copley Square Farmers Market","type":"market",
     "address":"139 St James Ave, Boston, MA 02116","coordinates":[-71.0749,42.3497],
     "snap":True,"free":False,"hours":"Tue & Fri 11am-6pm","tract_id":"25025080900","source":"seed"},
    # ── Roxbury ──────────────────────────────────────────────────────────────
    {"resource_id":"seed-r01","name":"Roxbury Community Health Center Pantry","type":"pantry",
     "address":"435 Warren St, Roxbury, MA 02119","coordinates":[-71.0839,42.3246],
     "snap":True,"free":True,"hours":"Mon-Fri 9am-5pm","tract_id":"25025081600","source":"seed"},
    {"resource_id":"seed-r02","name":"Tropical Foods International","type":"grocery",
     "address":"450 Melnea Cass Blvd, Roxbury, MA 02119","coordinates":[-71.0823,42.3311],
     "snap":True,"free":False,"tract_id":"25025081600","source":"USDA"},
    {"resource_id":"seed-r03","name":"Dudley Farmers Market","type":"market",
     "address":"427 Dudley St, Roxbury, MA 02119","coordinates":[-71.0832,42.3277],
     "snap":True,"free":False,"hours":"Sat 10am-3pm","tract_id":"25025081600","source":"USDA"},
    {"resource_id":"seed-r04","name":"Warren Gardens Resident Pantry","type":"pantry",
     "address":"10 Cheney St, Roxbury, MA 02119","coordinates":[-71.0861,42.3239],
     "snap":True,"free":True,"tract_id":"25025081600","source":"seed"},
    {"resource_id":"seed-r05","name":"GBFB Mobile Market — Roxbury","type":"mobile",
     "address":"Malcolm X Blvd & Shawmut Ave, Roxbury, MA","coordinates":[-71.0807,42.3242],
     "snap":False,"free":True,"hours":"Wed 10am-2pm","tract_id":"25025081600","source":"seed"},
    # ── South End / Back Bay ─────────────────────────────────────────────────
    {"resource_id":"seed-s01","name":"South End Food Pantry","type":"pantry",
     "address":"95 Berkeley St, Boston, MA 02116","coordinates":[-71.0717,42.3449],
     "snap":True,"free":True,"hours":"Mon-Sat 10am-4pm","tract_id":"25025080900","source":"seed"},
    {"resource_id":"seed-s02","name":"Shaw's Back Bay","type":"grocery",
     "address":"53 Huntington Ave, Boston, MA 02116","coordinates":[-71.0828,42.3480],
     "snap":True,"free":False,"tract_id":"25025080900","source":"seed"},
    {"resource_id":"seed-s03","name":"South End Farmers Market","type":"market",
     "address":"Columbus Ave & Dartmouth St, Boston, MA","coordinates":[-71.0695,42.3439],
     "snap":True,"free":False,"hours":"Sat 9am-1pm","tract_id":"25025080900","source":"seed"},
    {"resource_id":"seed-s04","name":"Boston Rescue Mission Mobile Kitchen","type":"mobile",
     "address":"39 Kingston St, Boston, MA 02111","coordinates":[-71.0572,42.3591],
     "snap":False,"free":True,"tract_id":"25025030100","source":"seed"},
    # ── Downtown / Charlestown ───────────────────────────────────────────────
    {"resource_id":"seed-d01","name":"Boston Public Market","type":"market",
     "address":"136 Blackstone St, Boston, MA 02202","coordinates":[-71.0545,42.3605],
     "snap":True,"free":False,"hours":"Tue-Sun 8am-8pm","tract_id":"25025030100","source":"USDA"},
    {"resource_id":"seed-d02","name":"Whole Foods Downtown","type":"grocery",
     "address":"181 Cambridge St, Boston, MA 02114","coordinates":[-71.0632,42.3556],
     "snap":True,"free":False,"hours":"Daily 7am-10pm","tract_id":"25025030100","source":"seed"},
    {"resource_id":"seed-d03","name":"St. Francis House Pantry","type":"pantry",
     "address":"39 Boylston St, Boston, MA 02116","coordinates":[-71.0593,42.3568],
     "snap":False,"free":True,"hours":"Mon-Fri 8am-4pm","tract_id":"25025030100","source":"seed"},
    {"resource_id":"seed-d04","name":"Market Basket Charlestown","type":"grocery",
     "address":"3 Rutherford Ave, Charlestown, MA 02129","coordinates":[-71.0679,42.3785],
     "snap":True,"free":False,"tract_id":"25025000301","source":"seed"},
    {"resource_id":"seed-d05","name":"Charlestown Pantry","type":"pantry",
     "address":"33 White St, Charlestown, MA 02129","coordinates":[-71.0631,42.3755],
     "snap":True,"free":True,"tract_id":"25025000301","source":"seed"},
    # ── Dorchester ───────────────────────────────────────────────────────────
    {"resource_id":"seed-do01","name":"Dorchester Winter Farmers Market","type":"market",
     "address":"6 Norfolk St, Dorchester, MA 02124","coordinates":[-71.0671,42.3049],
     "snap":True,"free":False,"hours":"Sat 10am-2pm","tract_id":"25025092101","source":"USDA"},
    {"resource_id":"seed-do02","name":"Truong Thinh II Market","type":"grocery",
     "address":"1305 Dorchester Ave, Dorchester, MA 02122","coordinates":[-71.0682,42.3022],
     "snap":True,"free":False,"tract_id":"25025092101","source":"USDA"},
    {"resource_id":"seed-do03","name":"Stop & Shop South Bay","type":"grocery",
     "address":"1150 Massachusetts Ave, Dorchester, MA 02125","coordinates":[-71.0619,42.3201],
     "snap":True,"free":False,"tract_id":"25025092301","source":"seed"},
    {"resource_id":"seed-do04","name":"Mobile Food Truck — Dorchester","type":"mobile",
     "address":"1234 Dorchester Ave, Dorchester, MA","coordinates":[-71.0691,42.3052],
     "snap":False,"free":True,"hours":"Thu 11am-2pm","tract_id":"25025092101","source":"seed"},
    # ── Jamaica Plain ────────────────────────────────────────────────────────
    {"resource_id":"seed-j01","name":"Whole Foods Jamaica Plain","type":"grocery",
     "address":"415 Centre St, Jamaica Plain, MA 02130","coordinates":[-71.1131,42.3172],
     "snap":True,"free":False,"hours":"Daily 7am-10pm","tract_id":"25025100800","source":"seed"},
    {"resource_id":"seed-j02","name":"JP Farmers Market","type":"market",
     "address":"18 Marbury Terrace, Jamaica Plain, MA 02130","coordinates":[-71.1115,42.3123],
     "snap":True,"free":False,"hours":"Wed 12pm-6pm","tract_id":"25025100800","source":"USDA"},
    {"resource_id":"seed-j03","name":"Community Servings Food Pantry","type":"pantry",
     "address":"179 Amory St, Jamaica Plain, MA 02130","coordinates":[-71.1086,42.3141],
     "snap":False,"free":True,"tract_id":"25025100800","source":"seed"},
    {"resource_id":"seed-j04","name":"Hi-Lo Foods JP","type":"grocery",
     "address":"415 Centre St, Jamaica Plain, MA 02130","coordinates":[-71.1149,42.3159],
     "snap":True,"free":False,"tract_id":"25025100800","source":"seed"},
    # ── East Boston ──────────────────────────────────────────────────────────
    {"resource_id":"seed-e01","name":"Eagle Market East Boston","type":"grocery",
     "address":"198 Maverick St, East Boston, MA 02128","coordinates":[-71.0378,42.3710],
     "snap":True,"free":False,"tract_id":"25025000202","source":"USDA"},
    {"resource_id":"seed-e02","name":"East Boston Health Center Pantry","type":"pantry",
     "address":"10 Gove St, East Boston, MA 02128","coordinates":[-71.0388,42.3678],
     "snap":False,"free":True,"hours":"Mon-Fri 9am-4pm","tract_id":"25025000202","source":"seed"},
    {"resource_id":"seed-e03","name":"Mobile Pantry East Boston","type":"mobile",
     "address":"Maverick Square, East Boston, MA","coordinates":[-71.0412,42.3694],
     "snap":False,"free":True,"hours":"Tue 10am-1pm","tract_id":"25025000202","source":"seed"},
    # ── Mattapan ─────────────────────────────────────────────────────────────
    {"resource_id":"seed-m01","name":"Mattapan Farmers Market","type":"market",
     "address":"525 River St, Mattapan, MA 02126","coordinates":[-71.0928,42.2730],
     "snap":True,"free":False,"hours":"Sat 9am-1pm","tract_id":"25025120400","source":"USDA"},
    {"resource_id":"seed-m02","name":"Mattapan Food Pantry","type":"pantry",
     "address":"90 Cummins Hwy, Mattapan, MA 02126","coordinates":[-71.0960,42.2761],
     "snap":True,"free":True,"tract_id":"25025120400","source":"seed"},
    {"resource_id":"seed-m03","name":"City Harvest Mobile — Mattapan","type":"mobile",
     "address":"River St & Cummins Hwy, Mattapan, MA","coordinates":[-71.0933,42.2780],
     "snap":False,"free":True,"hours":"Fri 11am-3pm","tract_id":"25025120400","source":"seed"},
    {"resource_id":"seed-m04","name":"Stop & Shop Mattapan","type":"grocery",
     "address":"1277 River St, Hyde Park, MA 02136","coordinates":[-71.0945,42.2753],
     "snap":True,"free":False,"tract_id":"25025120400","source":"seed"},
    # ── Hyde Park ────────────────────────────────────────────────────────────
    {"resource_id":"seed-h01","name":"Star Market Hyde Park","type":"grocery",
     "address":"1377 Hyde Park Ave, Hyde Park, MA 02136","coordinates":[-71.1264,42.2558],
     "snap":True,"free":False,"tract_id":"25025130400","source":"USDA"},
    {"resource_id":"seed-h02","name":"Hyde Park Farmers Market","type":"market",
     "address":"Hyde Park Ave & Cleary Square, MA","coordinates":[-71.1264,42.2558],
     "snap":True,"free":False,"hours":"Thu 3pm-7pm","tract_id":"25025130400","source":"seed"},
    {"resource_id":"seed-h03","name":"Hyde Park Food Pantry","type":"pantry",
     "address":"1110 Hyde Park Ave, Hyde Park, MA 02136","coordinates":[-71.1299,42.2513],
     "snap":True,"free":True,"tract_id":"25025130400","source":"seed"},
    # ── Allston / Brighton ───────────────────────────────────────────────────
    {"resource_id":"seed-a01","name":"Star Market Allston","type":"grocery",
     "address":"60 Everett St, Allston, MA 02134","coordinates":[-71.1420,42.3503],
     "snap":True,"free":False,"tract_id":"","source":"seed"},
    {"resource_id":"seed-a02","name":"GBFB Mobile Market — Brighton","type":"mobile",
     "address":"20 Fordham Rd, Brighton, MA 02135","coordinates":[-71.1512,42.3502],
     "snap":True,"free":True,"hours":"Mon 10am-2pm","tract_id":"","source":"seed"},
    {"resource_id":"seed-a03","name":"Harvest Co-op Allston","type":"grocery",
     "address":"57 South St, Jamaica Plain, MA 02130","coordinates":[-71.1319,42.3478],
     "snap":True,"free":False,"hours":"Daily 8am-9pm","tract_id":"","source":"seed"},
    # ── Mission Hill / Longwood ───────────────────────────────────────────────
    {"resource_id":"seed-mh01","name":"Mission Hill Farmers Market","type":"market",
     "address":"Calumet St & Tremont St, Mission Hill, MA","coordinates":[-71.1023,42.3333],
     "snap":True,"free":False,"hours":"Fri 3pm-7pm","tract_id":"","source":"seed"},
    {"resource_id":"seed-mh02","name":"Stop & Shop Mission Hill","type":"grocery",
     "address":"1100 Huntington Ave, Boston, MA 02115","coordinates":[-71.0998,42.3341],
     "snap":True,"free":False,"tract_id":"","source":"seed"},
    {"resource_id":"seed-mh03","name":"Longwood Medical Food Pantry","type":"pantry",
     "address":"330 Brookline Ave, Boston, MA 02215","coordinates":[-71.1058,42.3372],
     "snap":False,"free":True,"hours":"Tue & Thu 10am-2pm","tract_id":"","source":"seed"},
    # ── South Boston ─────────────────────────────────────────────────────────
    {"resource_id":"seed-sb01","name":"Roche Bros. South Boston","type":"grocery",
     "address":"516 E Broadway, South Boston, MA 02127","coordinates":[-71.0470,42.3375],
     "snap":True,"free":False,"tract_id":"","source":"seed"},
    {"resource_id":"seed-sb02","name":"South Boston Food Pantry","type":"pantry",
     "address":"388 Old Colony Ave, South Boston, MA","coordinates":[-71.0492,42.3329],
     "snap":True,"free":True,"tract_id":"","source":"seed"},
    {"resource_id":"seed-sb03","name":"Mobile Food Truck — South Boston","type":"mobile",
     "address":"Old Colony Ave & Dorchester St, South Boston, MA","coordinates":[-71.0501,42.3351],
     "snap":False,"free":True,"hours":"Mon 10am-1pm","tract_id":"","source":"seed"},
    # ── Cambridge border ─────────────────────────────────────────────────────
    {"resource_id":"seed-c01","name":"Whole Foods Cambridge","type":"grocery",
     "address":"340 River St, Cambridge, MA 02139","coordinates":[-71.1061,42.3625],
     "snap":True,"free":False,"hours":"Daily 7am-10pm","tract_id":"","source":"seed"},
    {"resource_id":"seed-c02","name":"Cambridge Food Pantry","type":"pantry",
     "address":"8 Cameron Ave, Cambridge, MA 02140","coordinates":[-71.1091,42.3741],
     "snap":False,"free":True,"tract_id":"","source":"seed"},
]


# ─────────────────────────────────────────────────────────────────────────────
# Seed runner
# ─────────────────────────────────────────────────────────────────────────────

def seed():
    print("=== FoodGrid Boston — seed_mock_data ===\n")

    # ── Tracts ────────────────────────────────────────────────────────────────
    tracts = build_tracts_from_geojson()
    print(f"Loaded {len(tracts)} tracts from {GEOJSON_PATH.name}.")

    col_t = tracts_col()
    # Clear stale tracts so old FIPS codes from previous seeds don't accumulate
    deleted = col_t.delete_many({}).deleted_count
    if deleted:
        print(f"  Cleared {deleted} stale tracts.")
    t_upserted = 0
    for tract in tracts:
        r = col_t.update_one(
            {"tract_id": tract["tract_id"]},
            {"$set": tract},
            upsert=True,
        )
        if r.upserted_id or r.modified_count:
            t_upserted += 1
    print(f"Tracts   : {t_upserted}/{len(tracts)} upserted.")

    # ── Resources ─────────────────────────────────────────────────────────────
    col_r = resources_col()
    r_upserted = 0
    for resource in RESOURCES:
        r = col_r.update_one(
            {"resource_id": resource["resource_id"]},
            {"$set": resource},
            upsert=True,
        )
        if r.upserted_id or r.modified_count:
            r_upserted += 1
    print(f"Resources: {r_upserted}/{len(RESOURCES)} upserted.")

    # ── City stats ────────────────────────────────────────────────────────────
    # Compute from the loaded tract data for accuracy
    scores = [t["food_risk_score"] for t in tracts]
    avg_equity = round(sum(1 - s for s in scores) / len(scores), 3)
    avg_transit = round(sum(t["transit_coverage"] for t in tracts) / len(tracts), 3)
    high_risk   = sum(1 for s in scores if s >= 0.65)

    city_stats = {
        "_id":             "singleton",
        "_type":           "city_stats",
        "equity_score":    avg_equity,
        "transit_coverage": avg_transit,
        "high_risk_tracts": high_risk,
        "total_tracts":    len(tracts),
    }
    city_stats_col().update_one(
        {"_id": "singleton"},
        {"$set": city_stats},
        upsert=True,
    )
    print(f"City stats: updated (total_tracts={len(tracts)}, high_risk={high_risk}).")

    print("\nDone. MongoDB collections are ready for development.")


if __name__ == "__main__":
    seed()
